name: Daily Test (@v1)

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the latest League of Legends Data Dragon
        id: dragon-tail
        uses: mikaeldui/download-league-of-legends-data-dragon@v1
        
      - name: Test result
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            fileExists('dragontail.tgz', () => fileExists('dragontail.zip', () => core.setFailed('No Data Dragon downloaded!')));
            "${{ steps.dragon-tail.outputs.version }}".length === 0 && core.setFailed('No Data Dragon version!');
            "${{ steps.dragon-tail.outputs.path }}".length === 0 && core.setFailed('No Data Dragon path!');

            function fileExists(path, error) {
              fs.access(path, fs.F_OK, (err) => {
                if (err) {
                  error(err);
                  return
                }
              });
            }
